# Site
title:              Steven Knight Kukard
bio:                'Composer of music for film, theatre and games'
description:        "Music for film, theatre and games"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.stevenknightkukard.com" # the base hostname & protocol for your site

# Captcha
captcha-site-key: 6LdkANAUAAAAAGlCOPX2oNatBnJz2WMjlYgKpTaN
captcha-secret-key: 6LdkANAUAAAAAJcVQebkjxNZwlNIv8g0Xs0h6_gf

# Comments
disqus_shortname:   default

# Social
analytics-id:       "default"
twitter:            default
facebook:           default
instagram:          default
github:             default

# personal
location:           Cape Town, South Africa
phone:
email:              stevenkukard@gmail.com # change this to your email to receive free emails for your contact submissions via Slapform.com

# Other
background_image:   /images/bg.jpg
# Tip: The color palette and other styles can be configured in /_sass/lib/_vars.scss
slapform_thankyou_page: /thank-you

defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author:

# Jekyll
permalink:          /blog/:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Gems
gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page:num/"

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
